src/Entity/Lieu.php
<?php

namespace App\Entity;

use App\Repository\LieuRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LieuRepository::class)
 */
class Lieu
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30, unique=true, nullable=false)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=30, nullable=false)
     */
    private $rue;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $longitude;

    /**
     * @ORM\ManyToOne(targetEntity=Ville::class, inversedBy="lieux")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_ville;

    /**
     * @ORM\OneToMany(targetEntity=Sortie::class, mappedBy="lieu")
     */
    private $sorties;

    public function __construct()
    {
        $this->sorties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getRue(): ?string
    {
        return $this->rue;
    }

    public function setRue(?string $rue): self
    {
        $this->rue = $rue;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(?float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(?float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getIdVille(): ?Ville
    {
        return $this->id_ville;
    }

    public function setIdVille(?Ville $id_ville): self
    {
        $this->id_ville = $id_ville;

        return $this;
    }

    /**
     * @return Collection|Sortie[]
     */
    public function getSorties(): Collection
    {
        return $this->sorties;
    }

    public function addSorty(Sortie $sorty): self
    {
        if (!$this->sorties->contains($sorty)) {
            $this->sorties[] = $sorty;
            $sorty->setLieu($this);
        }

        return $this;
    }

    public function removeSorty(Sortie $sorty): self
    {
        if ($this->sorties->removeElement($sorty)) {
            // set the owning side to null (unless already changed)
            if ($sorty->getLieu() === $this) {
                $sorty->setLieu(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
     return $this->nom;
    }
}

src/Entity/Sortie.php
<?php

namespace App\Entity;

use App\Repository\SortieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SortieRepository::class)
 */
class Sortie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_heure_debut;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duree;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_cloture;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_max_inscrits;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Etat::class, inversedBy="sorties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $etat;


    /**
     * @ORM\ManyToOne(targetEntity=Lieu::class, inversedBy="sorties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $lieu;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="sorties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $organisateur;

    /**
     * @ORM\ManyToMany(targetEntity=Utilisateur::class, inversedBy="sorties")
     */
    private $participants;

    public function __construct()
    {
        $this->participants = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getOrganisateur()
    {
        return $this->organisateur;
    }

    /**
     * @param mixed $organisateur
     */
    public function setOrganisateur($organisateur): void
    {
        $this->organisateur = $organisateur;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateHeureDebut(): ?\DateTimeInterface
    {
        return $this->date_heure_debut;
    }

    public function setDateHeureDebut(\DateTimeInterface $date_heure_debut): self
    {
        $this->date_heure_debut = $date_heure_debut;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(?int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getDateCloture(): ?\DateTimeInterface
    {
        return $this->date_cloture;
    }

    public function setDateCloture(\DateTimeInterface $date_cloture): self
    {
        $this->date_cloture = $date_cloture;

        return $this;
    }

    public function getNbMaxInscrits(): ?int
    {
        return $this->nb_max_inscrits;
    }

    public function setNbMaxInscrits(int $nb_max_inscrits): self
    {
        $this->nb_max_inscrits = $nb_max_inscrits;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEtat(): ?Etat
    {
        return $this->etat;
    }

    public function setEtat(?Etat $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getLieu(): ?Lieu
    {
        return $this->lieu;
    }

    public function setLieu(?Lieu $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    /**
     * @return Collection|Utilisateur[]
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Utilisateur $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
        }

        return $this;
    }

    public function removeParticipant(Utilisateur $participant): self
    {
        $this->participants->removeElement($participant);

        return $this;
    }
}

src/Controller/AccueilController.php
<?php

namespace App\Controller;

use App\Entity\Lieu;
use App\Entity\Sortie;
//use App\Entity\SortieUtilisateur;
//use App\Entity\Utilisateur;
use App\Entity\Ville;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AccueilController extends AbstractController
{
    /**
     * @Route("/accueil", name="accueil")
     */
    public function accueil(): Response
    {
        $user = $this->get('security.token_storage')->getToken()->getUser();
//        $utilisateursSorties = $this->getDoctrine()->getRepository(SortieUtilisateur::class)->findBy(["utilisateur_id"=>$user->getId()]);
        //$userSorties = $this->getDoctrine()->getRepository(SortieUtilisateur::class)->findAll();
        $sorties = $this->getDoctrine()->getRepository(Sortie::class)->findAll();
        $villes = $this->getDoctrine()->getRepository(Ville::class)->findAll();
        $lieux = $this->getDoctrine()->getRepository(Lieu::class)->findBy([], ["nom" => "ASC"]);

        return $this->render('accueil/accueil.html.twig', [
            'villes' => $villes,
            'lieux' => $lieux,
            'userCookie' => $user,
            'sorties' => $sorties,
            //'userSorties'=> $userSorties,
//            'utilisateursSorties'=> $utilisateursSorties
        ]);
    }
}

templates/accueil/accueil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

	{% block css %}
        <link rel="stylesheet" href="{{ asset('css/accueil.css') }}">
    {% endblock %}

{% block main %}
    <div class="h1-container">
        <div class="h1-style">
            <h1>Les sorties</h1>
            <div class="h1-underline"></div>
        </div>
    </div>

    {# <div class="filtres-container"> #}
    {# <h3>Filtrer les sorties</h3> #}
    {# <div class="filtres-form"> #}
    {# <div class="filtres-search"> #}
    {# <div class="filtre-site">Lieu :</div> #}
    {# <div class="filtre-site-combo"> #}
    {# <select name="sites" id="sites"> #}
    {# <option value="">--Choisissez un lieu--</option> #}
    {# {% for lieu in lieux %} #}
    {# <option value="{{ lieu.id }}">{{ lieu.nom }}</option> #}
    {# {% endfor %} #}
    {# </select> #}
    {# </div> #}
    {# </div> #}
    {# <div class="filtres-checkboxes"></div> #}
    {# <div class="filtres-button-go"></div> #}
    {# </div> #}
    {# </div> #}

    <div class="sorties-tablau">
        <div class="sortie-ligne">
            <div class="sortie-nom"><b>Nom de la sortie</b></div>
            <div class="sortie-ville">Ville</div>
            <div class="sortie-date"><b>Date de sortie</b></div>
            <div class="sortie-cloture"><b>Date de clôture</b></div>
            <div class="sortie-inscrits"><b>Max Inscrits</b></div>
            <div class="sortie-etat"><b>État</b></div>
            <div class="sortie-inscrit"><b>Inscrit</b></div>
            <div class="sortie-organisateur"><b>Organisateur</b></div>
            <div class="sortie-actions"><b>Actions</b></div>
        </div>
        {% set isOrganisateur, isParticipant = false, false %}
        {% for sortie in sorties %}
            {% if sortie.organisateur.pseudo == app.user.pseudo %}
                {% set isOrganisateur = true %}
            {% else %}
                {% set isOrganisateur = false %}
            {% endif %}
            {% for participant in sortie.participants %}
                {% if participant.pseudo == app.user.pseudo %}
                    {% set isParticipant = true %}
                {% else %}
                    {% set isParticipant = false %}
                {% endif %}
            {% endfor %}
            <div class="sortie-ligne">
                <div class="sortie-nom sortie-ligne-entete"></div>
                <div class="sortie-ville sortie-ligne-entete"></div>
                <div class="sortie-date sortie-ligne-entete"></div>
                <div class="sortie-cloture sortie-ligne-entete"></div>
                <div class="sortie-inscrits sortie-ligne-entete"></div>
                <div class="sortie-etat sortie-ligne-entete"></div>
                <div class="sortie-inscrit sortie-ligne-entete"></div>
                <div class="sortie-organisateur sortie-ligne-entete"></div>
                <div class="sortie-actions sortie-ligne-entete"></div>
            </div>
            <div class="sortie-ligne">
                <div class="sortie-nom"><a href="detail_sortie"><img src="{{ asset('icons/search.svg') }}"
                                                         alt="loupe"></a> {{ sortie.nom }}</div>
                <div class="sortie-ville">{{ sortie.lieu.idVille.nom }}</div>
                <div class="sortie-date">{{ sortie.dateHeureDebut.format('d/m/Y H:i') }}</div>
                <div class="sortie-cloture">{{ sortie.dateCloture.format('d/m/Y H:i') }}</div>
                <div class="sortie-inscrits"> {{ sortie.nbMaxInscrits }}</div>
                <div class="sortie-etat">{{ sortie.etat }}</div>
                <div class="sortie-inscrit">

                    {% if isParticipant or isOrganisateur %}
                        <img src="{{ asset('icons/check.png') }}" alt="X" style="width: 2em;">
                    {% else %}
                        <div>Non inscrit</div>
                    {% endif %}
                </div>

                <div class="sortie-organisateur">{{ sortie.organisateur.pseudo }}</div>
                <div class="sortie-actions sortie-liens">

                    {% if isOrganisateur or is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('delete_sortie', {'id':sortie.id}) }}"
                           onclick="confirm('Êtes vous sûr de vouloir supprimer ?') || event.preventDefault()">Supprimer</a>
                        <a href="{{ path('modifier_sortie', {'id':sortie.id}) }}">Modifier</a>
                    {% endif %}

                    {% if isParticipant and not isOrganisateur %}
                        <a href="#">Se désister</a>
                    {% endif %}

                    {% if not isOrganisateur and not isParticipant %}
                        <a href="{{ path('inscrit_toi', {'id':sortie.id, 'user_id':app.user.id}) }}"
                           onclick="confirm('Êtes vous sûr de vouloir inscrire ?') || event.preventDefault()">M'inscrire</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
    <a href="{{ path('nouvelle_sortie') }}" class="icon-add" style="margin-left: 8em;"><img
                src="{{ asset('icons/add_3.png') }}"
                alt="Créer" title="Ajouter une sortie" style="width: 2.1em;"></a>

{% endblock %}

templates/accueil/entree.html.twig
{% extends 'base.html.twig' %}

{# {% block title %}{% endblock %} #}

	{% block css %}
		<link rel="stylesheet" href="{{ asset('css/app.css') }}">
		<link rel="stylesheet" href="{{ asset('css/entree.css') }}">
	{% endblock %}


{% block main %}
	<div class="h1-container">
		<div class="h1-style">
			<h1>Bienvenue</h1>
			<div class="h1-underline"></div>
		</div>
	</div>
	<div class="accueil-presentation">
		<div class="presentation-images"></div>
		<div class="presentation-text">
			Sortir.com est un site de
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam asperiores at quod ratione veniam.
				Accusamus cum debitis, excepturi itaque iure libero maiores obcaecati sapiente sed sequi similique sit
				voluptate voluptatum!</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam asperiores at quod ratione veniam.
				Accusamus cum debitis, excepturi itaque iure libero maiores obcaecati sapiente sed sequi similique sit
				voluptate voluptatum!</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam asperiores at quod ratione veniam.
				Accusamus cum debitis, excepturi itaque iure libero maiores obcaecati sapiente sed sequi similique sit
				voluptate voluptatum!</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam asperiores at quod ratione veniam.
				Accusamus cum debitis, excepturi itaque iure libero maiores obcaecati sapiente sed sequi similique sit
				voluptate voluptatum!</p>
		</div>
	</div>
{% endblock %}

templates/accueil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AccueilController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'D:/xampp/php/www/Uswap/src/Controller/AccueilController.php'|file_link(0) }}">src/Controller/AccueilController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'D:/xampp/php/www/Uswap/templates/accueil/index.html.twig'|file_link(0) }}">templates/accueil/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}